image: mcr.microsoft.com/dotnet/core/sdk:3.1.201

stages:
  - test
    
debug:
  before_script:
   - 'echo | dotnet --version' 
   - dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

  stage: test

  script:

    - dotnet test --logger "junit"
    artifacts:
      reports:
        junit:
          - 'tests/*/TestResults/TestResults.xml'
