image: mcr.microsoft.com/dotnet/core/sdk:3.1.201

stages:
  - test
    
debug:
  before_script:
   - 'echo | dotnet --version' 
   - dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

  stage: test

  script:

    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --logger "junit" --collect:"XPlat Code Coverage"
    - echo 'End Summary'
    artifacts:
      reports:
        junit:
          - '*.Test/TestResults/TestResults.xml'
