name: .NET

on:
  push:
    branches: [ master, video_processing ]
  pull_request:
    branches: [ master, video_processing ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudp apt=get update
    - name: Install libc6-dev
      run: sudo apt-get install libc6-dev
    - name: Install libgdiplus
      run: sudo apt-get install libgdiplus
    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=\"lcov,json\" /p:CoverletOutput=../../CoverageResults/ /p:MergeWith='../../CoverageResults/coverage.json' -m:1
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: CoverageResults/coverage.info 
